### ISSUE TITLE
minor copyright/licensing corrections

### ISSUE THREAD

**Issue by onlyjob** [chengsun/moz-spdy-indicator#10]
It would be nice if license would be accompanied with proper copyright statement, something like the following:

~~~~
Copyright: 2012 Cheng Sun <spdyindicator@chengsun.github.com>
~~~~

Also please consider correcting the icon license: instead of "CC" it should be "CC-BY-3.0".

Thank you for awesome extension. :)

**Comment by chengsun** [comment]
Fixed by https://github.com/chengsun/moz-spdy-indicator/commit/de8a65e6f0f07da2f071a9033b82004b87041661. Thanks.
