### ISSUE TITLE
icon is not green - yet spdycheck.org is all green

### ISSUE THREAD

**Issue by propertunist** [chengsun/moz-spdy-indicator#11]
i am testing spdy for the 1st time here.
spdycheck.org now shows all green results for my site.. yet this firefox plugin is not lit up green like it is when i look at, for example, facebook.

my site is here: www.infiniteeureka.com

any tips welcomed

**Comment by chengsun** [comment]
Can you still confirm this bug? Works for me.

**Comment by propertunist** [comment]
i just tested again with the latest version of the code from the mozilla add-in repo.. and i can now see the correct output.
