### ISSUE TITLE
showing only portion of website with spdy active

### ISSUE THREAD

**Issue by BernardA** [chengsun/moz-spdy-indicator#15]
The extension shows that SPDY is active for sub-documents in some pages of website, while others show as fully active.

sub-documents only = www.soeezauto.ma

fully active = www.soeezauto.ma/soeez-blog/

Running trace also shows that it's active (https://www.soeezauto.ma/cdn-cgi/trace):

fl=4f3
h=www.soeezauto.ma
ip=2400:cb00:f00d:5ca1:498c:f527:954:1a29
ts=1427310305.107
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:36.0) Gecko/20100101 Firefox/36.0
colo=SJC
spdy=3.1
0

Note that the Chrome extension equivalent shows it as active on all pages.

What can cause this behaviour?

Thanks
Bernard

**Comment by bsiegel** [comment]
Unable to reproduce this with v3.0beta1, presuming fixed. If you see this issue occurring with v3.0+, please file a new issue here: https://github.com/bsiegel/http2-indicator/issues
