### ISSUE TITLE
I dont see the icon when a HTTP2 website is recognized as "reader view" compatible

### ISSUE THREAD

**Issue by jcea** [chengsun/moz-spdy-indicator#16]
When I browse a HTTP2 website I see the HTTP2 icon indicator if the website is not "reader view" compatible, but I don't see the icon when the website is "reader view" compatible and its icon is displayed.

If I disable the "reader view" thru about:config, I see HTTP2 icon correctly displayed.

**Comment by jcea** [comment]
This happens since I upgraded to Firefox 42.

**Comment by bsiegel** [comment]
Unable to reproduce this with v3.0beta1, presuming fixed. If you see this issue occurring with v3.0+, please file a new issue here: https://github.com/bsiegel/http2-indicator/issues
