### ISSUE TITLE
Http2 Indicator Not Working on Mozilla Developer Edition

### ISSUE THREAD

**Issue by 4nanook** [chengsun/moz-spdy-indicator#19]
I've installed the HTTP2 indicator, did a restart even though it said it was not necessary, but it still isn't giving me any indication that a site I know is capable of http2 is.  No lightning bolt at all, grey, blue, or
otherwise on 46.0a2 developer edition.

**Comment by chengsun** [comment]
Should be fixed with version 2.3 (pending review on AMO). Report back if you still have issues.
