### ISSUE TITLE
Seamonkey compatiblity

### ISSUE THREAD

**Issue by MPeairs** [chengsun/moz-spdy-indicator#2]
The just released Seamonkey 2.8 has spdy support though it's turned off by default and the nightly version 11 has it on by default so I made the following changes and tested it with version 7.2, 8 and 11a

Added to install.rdf:

 em:targetApplication
      <Description> 
        em:id{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}/em:id
        em:minVersion2.7/em:minVersion
        em:maxVersion3.0+/em:maxVersion
      </Description>
    /em:targetApplication

Changed one line in chrome.manifest :

overlay chrome://browser/content/browser.xul chrome://spdyindicator/content/overlay.xul

into:
# firefox overlay

overlay chrome://browser/content/browser.xul chrome://spdyindicator/content/overlay.xul application={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
# seamonkey overlay

overlay chrome://navigator/content/navigator.xul chrome://spdyindicator/content/overlay.xul application={92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}

Thanks for the neat addon!

**Comment by bsiegel** [comment]
Closing as Won't Fix. Not sure if this even applies to the WebExtension version.
