### ISSUE TITLE
icon is blurry on Retina display

### ISSUE THREAD

**Issue by Kolcha** [chengsun/moz-spdy-indicator#24]
Icon looks blurry (raster scaling) on Retina display.
Firefox 52 on macOS
<img width="179" alt="screenshot 2017-04-11 17 16 27" src="https://cloud.githubusercontent.com/assets/947647/24913849/1a181d64-1edb-11e7-9f26-4cf81d240f02.png">

**Comment by aleksandrs-ledovskis** [comment]
This was fixed in https://github.com/chengsun/moz-spdy-indicator/pull/22

Apparently, add-on wasn't updated on addons.mozilla.org. Ping @chengsun ?

**Comment by bsiegel** [comment]
Sorry for the delay, this was included in https://github.com/chengsun/moz-spdy-indicator/releases/tag/v2.4
