### ISSUE TITLE
Firefox 57 update?

### ISSUE THREAD

**Issue by Septdir** [chengsun/moz-spdy-indicator#26]
will there be an update for firefox 57?

**Comment by bsiegel** [comment]
@Septdir Version 3.0beta1 is available in the Development Channel: https://addons.mozilla.org/en-US/firefox/addon/spdy-indicator/versions/beta - please let me know if you experience any issues! Once I'm reasonably confident that it's stable and matches feature parity with the legacy version, I'll roll it out to everyone.
