### ISSUE TITLE
Version 3.0, Loss of Grey Indicator for Sub-Level Documents

### ISSUE THREAD

**Issue by MarkRH** [chengsun/moz-spdy-indicator#27]
In my testing of Firefox 57 I noticed this just updated and it seems to work fine on Twitter, Google and so but in previous versions when going to site like my blog http://blog.markheadrick.com/ it would display a greyed icon indicating that sub-documents were, such as the Twitter widget.  Anyway, I have no idea if such  a thing is possible with all the changes that have occurred. 

Anyway, it's cool that this much is working now as a Web-Extension. Thanks for all your efforts. :)

**Comment by MarkRH** [comment]
Well, it does show the grey icon, just not there.  It is working on http://www.markheadrick.com/ which is loading similar widgets and it does show on my blog if I view a post with an embedded YouTube video so I dunno.  Might be non-issue then.

**Comment by bsiegel** [comment]
Thanks for the report - there may be some race condition causing this issue, I've noticed it rarely but not sure exactly the cause. In my browser I am seeing the gray indicator for both URLs you provided. The WebExtension version is being developed as a separate codebase, so I've filed a new issue to track this and linked your original bug report: https://github.com/bsiegel/http2-indicator/issues/2
